# Generated by Django 3.1.5 on 2021-01-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'точка на карте', 'verbose_name_plural': 'точки на карте'},
        ),
    ]
