# Generated by Django 3.1.5 on 2021-02-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210112_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='f', upload_to='', verbose_name='ИЗображение'),
            preserve_default=False,
        ),
    ]
