# Generated by Django 3.1.5 on 2021-01-10 17:11

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название категории')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание категории')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('seo_description', models.CharField(max_length=128, verbose_name='Заголовок страницы (SEO)')),
                ('important', models.BooleanField(verbose_name='Показывать в числе первых')),
                ('slug', models.SlugField(max_length=16, verbose_name='Slug (название в URL)')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название города')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('seo_description', models.CharField(max_length=128, verbose_name='Заголовок страницы (SEO)')),
                ('slug', models.SlugField(max_length=16, verbose_name='Slug (название в URL)')),
                ('tours_count', models.IntegerField(default=0, verbose_name='Количество туров в городе')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Количество заказов в городе')),
                ('image_city', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, verbose_name='Текст предложения')),
                ('color', models.CharField(choices=[('#4dc05e', 'Зелёный'), ('#ec4159', 'Красный')], max_length=7, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=16, verbose_name='Slug (название в URL)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание категории')),
                ('include', ckeditor.fields.RichTextField(verbose_name='Описание категории')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('seo_description', models.CharField(max_length=128, verbose_name='Заголовок страницы (SEO)')),
                ('seat_request', models.BooleanField(default=True, verbose_name="Показывать блок 'Запросить места'")),
                ('count_comment', models.SmallIntegerField(default=0, verbose_name='Количество отзывов')),
                ('rating', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (для главной)')),
                ('group', models.BooleanField(choices=[(True, 'Групповая'), (False, 'Одиночная')], verbose_name='Тип')),
                ('time', models.TimeField(verbose_name='Продолжительность экскурсии')),
                ('image', models.ImageField(upload_to='', verbose_name='Основная фотография')),
                ('categories', models.ManyToManyField(to='tours.Category')),
                ('city', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='tours.city')),
                ('offer', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.offer')),
                ('positions', models.ManyToManyField(to='maps.Position')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_add', to='tours.tour')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_main', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Основная фотография')),
                ('description', models.TextField(max_length=128, verbose_name='Описание фотографии')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя пользователя')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('grade', models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
            ],
        ),
    ]
