# Generated by Django 3.1.5 on 2021-01-13 07:56

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_auto_20210112_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название категории')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание категории')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('seo_description', models.CharField(max_length=128, verbose_name='Описание страницы (SEO)')),
                ('important', models.BooleanField(verbose_name='Показывать в числе первых')),
                ('slug', models.SlugField(max_length=16, unique=True, verbose_name='Slug (название в URL)')),
                ('city', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='base.city')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, verbose_name='Текст предложения')),
                ('color', models.CharField(choices=[('#4dc05e', 'Зелёный'), ('#ec4159', 'Красный')], max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'специальное предложение',
                'verbose_name_plural': 'специальные предложение',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название позиции')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'точка на карте',
                'verbose_name_plural': 'точки на карте',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название экскурсии')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug (название в URL)')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('seo_description', models.CharField(max_length=128, verbose_name='Описание страницы (SEO)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание экскурсии')),
                ('include', ckeditor.fields.RichTextField(verbose_name='Включено')),
                ('seat_request', models.BooleanField(default=True, verbose_name="Показывать блок 'Запросить места'")),
                ('count_comment', models.SmallIntegerField(default=0, verbose_name='Количество отзывов')),
                ('rating', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (для главной)')),
                ('group', models.BooleanField(choices=[(True, 'Групповая'), (False, 'Одиночная')], verbose_name='Тип')),
                ('time', models.CharField(max_length=32, verbose_name='Продолжительность экскурсии')),
                ('image', models.ImageField(upload_to='', verbose_name='Основная фотография')),
                ('notes', models.CharField(default='Пусто', max_length=64, verbose_name='Примечания')),
                ('categories', models.ManyToManyField(to='tours.Category', verbose_name='Категории')),
                ('city', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='base.city')),
                ('offer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tours.offer')),
                ('positions', models.ManyToManyField(to='tours.Position', verbose_name='Точки на карте')),
            ],
            options={
                'verbose_name': 'экскурсию',
                'verbose_name_plural': 'экскурсии',
            },
        ),
        migrations.CreateModel(
            name='RecommendedTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_add', to='tours.tour', verbose_name='Рекомендованная экскурсия')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_main', to='tours.tour', verbose_name='Основная экскурсия')),
            ],
            options={
                'verbose_name': 'Рекомендованная экскурсия',
                'verbose_name_plural': 'Рекомендованные экскурсии',
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Дополнительная фотография')),
                ('description', models.CharField(max_length=128, verbose_name='Описание фотографии')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
            ],
            options={
                'verbose_name': 'дополнительная фотография',
                'verbose_name_plural': 'дополнительные фотографии',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя пользователя')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('grade', models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
