# Generated by Django 3.1.5 on 2021-01-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'специальное предложение', 'verbose_name_plural': 'специальные предложение'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=16, unique=True, verbose_name='Slug (название в URL)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='seo_description',
            field=models.CharField(max_length=128, verbose_name='Описание страницы (SEO)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=16, unique=True, verbose_name='Slug (название в URL)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='tours_count',
            field=models.IntegerField(default=0, verbose_name='Количество экскурсий в городе'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Slug (название в URL)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.CharField(max_length=32, verbose_name='Продолжительность экскурсии'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название экскурсии'),
        ),
    ]
