# Generated by Django 3.1.5 on 2021-01-11 11:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210111_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'экскурсию', 'verbose_name_plural': 'экскурсии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
        migrations.AddField(
            model_name='tour',
            name='notes',
            field=models.TextField(default='Пусто', verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.CharField(max_length=128, verbose_name='Описание страницы (SEO)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание экскурсии'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='include',
            field=ckeditor.fields.RichTextField(verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='offer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='tours.offer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='seo_description',
            field=models.CharField(max_length=128, verbose_name='Описание страницы (SEO)'),
        ),
    ]
