# Generated by Django 3.1.5 on 2021-02-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210207_0930'),
        ('tours', '0003_auto_20210207_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('h1', models.CharField(max_length=64, verbose_name='Заговок h1')),
                ('h2', models.CharField(max_length=64, verbose_name='Заговок h1')),
                ('city', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='base.city')),
            ],
            options={
                'verbose_name': 'район',
                'verbose_name_plural': 'районы',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='towns',
            field=models.ManyToManyField(to='tours.Town', verbose_name='Районы'),
        ),
    ]
