# Generated by Django 3.1.5 on 2021-01-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20210111_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='notes',
            field=models.CharField(default='Пусто', max_length=64, verbose_name='Примечания'),
        ),
    ]
