# Generated by Django 3.1.5 on 2021-02-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20210208_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название города')),
                ('h1', models.CharField(max_length=32, verbose_name='Заголовок h1')),
                ('h2', models.CharField(max_length=32, verbose_name='Заголовок h2')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('seo_description', models.CharField(max_length=128, verbose_name='Описание страницы (SEO)')),
                ('slug', models.SlugField(max_length=16, unique=True, verbose_name='Slug (название в URL)')),
                ('tours_count', models.IntegerField(default=0, verbose_name='Количество экскурсий в городе')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Количество заказов в городе')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название кластера')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='towns',
        ),
        migrations.AlterField(
            model_name='tour',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.offer'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='Town',
        ),
        migrations.AddField(
            model_name='like',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour'),
        ),
    ]
