# Generated by Django 3.1.5 on 2021-01-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_city'),
        ('maps', '0002_auto_20210111_1411'),
        ('tours', '0005_auto_20210111_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': 'дополнительная фотография', 'verbose_name_plural': 'дополнительные фотографии'},
        ),
        migrations.AlterModelOptions(
            name='recommendedtour',
            options={'verbose_name': 'Рекомендованная экскурсия', 'verbose_name_plural': 'Рекомендованные экскурсии'},
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Дополнительная фотография'),
        ),
        migrations.AlterField(
            model_name='recommendedtour',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_add', to='tours.tour', verbose_name='Рекомендованная экскурсия'),
        ),
        migrations.AlterField(
            model_name='recommendedtour',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_main', to='tours.tour', verbose_name='Основная экскурсия'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(to='tours.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='base.city'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='positions',
            field=models.ManyToManyField(to='maps.Position', verbose_name='Точки на карте'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
