# Generated by Django 3.1.5 on 2021-02-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_category_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cities',
            field=models.ManyToManyField(related_name='add_cities', to='tours.City', verbose_name='Дополнительные'),
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='main_city', to='tours.city'),
        ),
    ]
