# Generated by Django 3.1.5 on 2021-02-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20210218_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.cluster'),
        ),
    ]
