# Generated by Django 3.1.5 on 2021-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_city_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='importance',
            field=models.PositiveIntegerField(default=0, verbose_name='Важность города в кластере'),
        ),
    ]
