# Generated by Django 3.1.5 on 2021-02-22 16:04

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_city_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'verbose_name': 'Кластер', 'verbose_name_plural': 'Кластеры'},
        ),
        migrations.AlterField(
            model_name='city',
            name='importance',
            field=models.PositiveIntegerField(default=0, verbose_name='Важность города'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cities',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='city', chained_model_field='cluster', horizontal=True, related_name='add_cities', to='tours.City', verbose_name='Дополнительные'),
        ),
    ]
