# Generated by Django 3.1.5 on 2021-02-23 08:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20210222_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(blank=True, to='tours.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='cluster', chained_model_field='cluster', on_delete=django.db.models.deletion.PROTECT, related_name='main_city', to='tours.city'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='offer',
            field=models.CharField(blank=True, max_length=20, verbose_name='Специальное предложение'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='positions',
            field=models.ManyToManyField(blank=True, to='tours.Position', verbose_name='Точки на карте'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
