# Generated by Django 3.1.5 on 2021-02-23 08:08

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20210223_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cities',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='cluster', chained_model_field='cluster', horizontal=True, related_name='add_cities', to='tours.City', verbose_name='Дополнительные'),
        ),
    ]
