# Generated by Django 3.1.5 on 2021-02-23 08:10

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_auto_20210223_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cities',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='cluster', chained_model_field='cluster', horizontal=True, related_name='add_cities', to='tours.City', verbose_name='Дополнительные города'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='cluster', chained_model_field='cluster', on_delete=django.db.models.deletion.PROTECT, related_name='main_city', to='tours.city', verbose_name='Основной город'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.cluster', verbose_name='Кластер'),
        ),
    ]
