# Generated by Django 3.1.5 on 2021-02-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_auto_20210223_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='city',
            name='h2',
        ),
    ]
