# Generated by Django 3.1.5 on 2021-02-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_auto_20210225_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
    ]
