# Generated by Django 3.1.5 on 2021-03-05 06:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_auto_20210305_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='add_price',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
