# Generated by Django 3.1.5 on 2021-03-05 06:55

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_auto_20210305_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='add_price',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
