# Generated by Django 3.1.5 on 2021-03-05 07:06

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_auto_20210305_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='include',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, default='{Трансфер в радиусе 5 км, Услуги гида}', size=4),
        ),
        migrations.AlterField(
            model_name='tour',
            name='add_price',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, size=4),
        ),
    ]
