# Generated by Django 3.1.5 on 2021-03-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0024_auto_20210305_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='add_price',
            new_name='add_price_list',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='include',
            new_name='include_list',
        ),
    ]
