# Generated by Django 3.1.5 on 2021-03-11 07:17

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_auto_20210305_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='advantages_list',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='add_price_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, size=6, verbose_name='За дополнительную плату'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='include_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, size=6, verbose_name='Включено'),
        ),
    ]
