# Generated by Django 3.1.5 on 2021-03-11 07:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0026_auto_20210311_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='advantages_list',
            field=jsonfield.fields.JSONField(),
        ),
    ]
