# Generated by Django 3.1.5 on 2021-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0027_auto_20210311_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='advantages_list',
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage1_description',
            field=models.CharField(blank=True, default='Бестлатно привезем и отвезем обратно', max_length=64, verbose_name='Трансфер (описание)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage1_title',
            field=models.CharField(blank=True, default='Трансфер предусмотрен', max_length=32, verbose_name='Трансфер (заголовок)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage2_description',
            field=models.CharField(blank=True, default='Экскурсия без посторонних людей', max_length=64, verbose_name='Группа/индвидуальная (описание)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage2_title',
            field=models.CharField(blank=True, default='Индивидуальная', max_length=32, verbose_name='Группа/индвидуальная (заголовок)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage3_description',
            field=models.CharField(blank=True, default='Включая 15-минутный инструктаж', max_length=64, verbose_name='Время (описание)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage3_title',
            field=models.CharField(blank=True, default='2 часа', max_length=32, verbose_name='Время (заголовок)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage4_description',
            field=models.CharField(blank=True, default='Дети старше 14 лет допусаются к управлению', max_length=64, verbose_name='Дети (описание)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage4_title',
            field=models.CharField(blank=True, default='Можно с детьми', max_length=32, verbose_name='Дети (заголовок)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage5_description',
            field=models.CharField(blank=True, default='Бронируйте экскурсию без предоплаты', max_length=64, verbose_name='Предоплата (описание)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='advantage5_title',
            field=models.CharField(blank=True, default='Без предоплаты', max_length=32, verbose_name='Предоплата (заголовок)'),
        ),
    ]
