# Generated by Django 3.1.5 on 2021-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0028_auto_20210311_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='advantage4_description',
            field=models.CharField(blank=True, default='Дети старше 14 лет допускаются к управлению', max_length=64, verbose_name='Дети (описание)'),
        ),
    ]
