# Generated by Django 3.1.5 on 2021-03-11 08:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0029_auto_20210311_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_mini',
            field=models.TextField(default='Мини описание', verbose_name='Описание экскурсии (мини)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание экскурсии (полное)'),
        ),
    ]
