# Generated by Django 3.1.5 on 2021-03-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0030_auto_20210311_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Описание экскурсии (полное)'),
        ),
    ]
