# Generated by Django 3.1.5 on 2021-03-11 08:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0031_auto_20210311_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание экскурсии (полное)'),
        ),
    ]
