# Generated by Django 3.1.5 on 2021-03-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0034_auto_20210324_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.TextField(blank=True, max_length=15, verbose_name='Телефон')),
                ('answer', models.BooleanField(default=False, verbose_name='Обработано')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
            ],
        ),
    ]
