# Generated by Django 3.1.5 on 2021-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0035_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
