# Generated by Django 3.1.5 on 2021-03-31 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0039_auto_20210331_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название переменной')),
                ('type', models.CharField(choices=[('r', 'Тариф'), ('a', 'Взрослые'), ('c', 'Дети')], max_length=1, verbose_name='Тип')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные для тарифов',
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='tour',
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Вариант переменной', 'verbose_name_plural': 'Варианты переменной'},
        ),
        migrations.RemoveField(
            model_name='rate',
            name='tour',
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.FloatField(verbose_name='Цена/Множитель'),
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='rate',
            name='variable',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='tours.variable'),
            preserve_default=False,
        ),
    ]
