# Generated by Django 3.1.5 on 2021-03-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0040_auto_20210331_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Цена/Множитель'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='variable',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tours.variable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Название переменной'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='tour',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(blank=True, choices=[('r', 'Тариф'), ('a', 'Взрослые'), ('c', 'Дети')], max_length=1, verbose_name='Тип'),
        ),
    ]
