# Generated by Django 3.1.5 on 2021-04-08 07:18

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0041_auto_20210331_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='start_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=4, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(blank=True, choices=[('r', 'Тариф'), ('g', 'Группа'), ('c', 'Дети')], max_length=1, verbose_name='Тип'),
        ),
    ]
