# Generated by Django 3.1.5 on 2021-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0042_auto_20210408_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='transfer',
            field=models.CharField(choices=[('y', 'Есть'), ('n', 'Нет'), ('yn', 'Есть + Нет')], default='yn', max_length=2, verbose_name='Трансфер'),
            preserve_default=False,
        ),
    ]
