# Generated by Django 3.1.5 on 2021-04-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0045_auto_20210413_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название периода')),
                ('january', models.BooleanField(verbose_name='Январь')),
                ('february', models.BooleanField(verbose_name='Февраль')),
                ('march', models.BooleanField(verbose_name='Март')),
                ('april', models.BooleanField(verbose_name='Апрель')),
                ('may', models.BooleanField(verbose_name='Май')),
                ('june', models.BooleanField(verbose_name='Июнь')),
                ('july', models.BooleanField(verbose_name='Июль')),
                ('august', models.BooleanField(verbose_name='Август')),
                ('september', models.BooleanField(verbose_name='Сентябрь')),
                ('october', models.BooleanField(verbose_name='Октябрь')),
                ('november', models.BooleanField(verbose_name='Ноябрь')),
                ('december', models.BooleanField(verbose_name='Декабрь')),
            ],
        ),
    ]
