# Generated by Django 3.1.5 on 2021-04-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0046_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='period',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='tours.period', verbose_name='Период года'),
            preserve_default=False,
        ),
    ]
