# Generated by Django 3.1.5 on 2021-04-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0049_advantage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='advantage1_description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage1_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage2_description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage2_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage3_description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage3_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage4_description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage4_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage5_description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='advantage5_title',
        ),
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Заголовок'),
        ),
    ]
