# Generated by Django 3.1.5 on 2021-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0051_auto_20210414_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='prepay_percent',
        ),
        migrations.AlterField(
            model_name='tour',
            name='prepay',
            field=models.PositiveIntegerField(verbose_name='Предоплата (%)'),
        ),
    ]
