# Generated by Django 3.1.5 on 2021-04-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0053_tour_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='image',
            new_name='icon',
        ),
    ]
