# Generated by Django 3.1.5 on 2021-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0054_auto_20210430_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
