# Generated by Django 3.1.5 on 2021-02-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
