# Generated by Django 3.1.5 on 2021-01-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=32, verbose_name='Название сайта')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('number_phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('user_agreement', models.TextField(verbose_name='Пользовательноское соглашение')),
                ('help_title', models.CharField(max_length=32, verbose_name="'Помощь в выборе' заголовок")),
                ('help_text', models.TextField(verbose_name="'Помощь в выборе' текст")),
                ('map_title', models.CharField(max_length=32, verbose_name="'Экскурсии на карте' заголовок")),
                ('map_text', models.TextField(verbose_name="'Экскурсии на карте' текст")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
        ),
    ]
