# Generated by Django 3.1.5 on 2021-01-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Конфиг', 'verbose_name_plural': 'Конфиг'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
