# Generated by Django 3.1.5 on 2021-01-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название города')),
                ('seo_title', models.CharField(max_length=64, verbose_name='Заговок страницы (SEO)')),
                ('seo_description', models.CharField(max_length=128, verbose_name='Описание страницы (SEO)')),
                ('slug', models.SlugField(max_length=16, unique=True, verbose_name='Slug (название в URL)')),
                ('tours_count', models.IntegerField(default=0, verbose_name='Количество экскурсий в городе')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Количество заказов в городе')),
                ('image_city', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
    ]
