# Generated by Django 3.1.5 on 2021-02-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210112_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='image_city',
            new_name='image',
        ),
    ]
