# Generated by Django 3.1.5 on 2021-02-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210207_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='h1',
            field=models.CharField(default='ff', max_length=32, verbose_name='Заголовок h1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='h2',
            field=models.CharField(default='ff', max_length=32, verbose_name='Заголовок h2'),
            preserve_default=False,
        ),
    ]
