# Generated by Django 3.1.5 on 2021-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210207_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='config',
            name='help_title',
        ),
        migrations.RemoveField(
            model_name='config',
            name='map_text',
        ),
        migrations.RemoveField(
            model_name='config',
            name='map_title',
        ),
        migrations.AddField(
            model_name='config',
            name='site_description',
            field=models.CharField(default='dd', max_length=32, verbose_name='Подзагловок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='site_name',
            field=models.CharField(max_length=32, verbose_name='Заголовок сайта'),
        ),
    ]
