# Generated by Django 3.1.5 on 2021-04-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0048_auto_20210414_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_order', models.DateTimeField(auto_created=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=64, verbose_name='Почта')),
                ('date_tour', models.DateField(verbose_name='Дата')),
                ('start_tour', models.TimeField(verbose_name='Начало')),
                ('rate', models.CharField(blank=True, max_length=32, verbose_name='Тариф')),
                ('group', models.CharField(blank=True, max_length=32, verbose_name='Группа')),
                ('children', models.CharField(blank=True, max_length=32, verbose_name='Дети')),
                ('amount', models.FloatField(verbose_name='Общая сумма заказа')),
                ('prepay', models.FloatField(verbose_name='Внесённая предоплата')),
                ('payment', models.FloatField(verbose_name='Остаток оплаты')),
                ('transfer', models.BooleanField(verbose_name='Трансфер')),
                ('commission_percent', models.IntegerField(verbose_name='Коммиссия (%)')),
                ('commission_money', models.FloatField(verbose_name='Коммисия (рубли)')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.position', verbose_name='Место встречи')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tour', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
