# Generated by Django 3.1.5 on 2021-04-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0052_auto_20210415_0919'),
        ('orders', '0002_auto_20210415_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tours.position', verbose_name='Место встречи'),
        ),
    ]
