# Generated by Django 3.1.5 on 2021-04-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0052_auto_20210415_0919'),
        ('orders', '0003_auto_20210415_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.position', verbose_name='Место встречи'),
        ),
    ]
