# Generated by Django 3.1.5 on 2021-04-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210415_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mail',
            field=models.CharField(blank=True, max_length=64, verbose_name='Почта'),
        ),
    ]
