# Generated by Django 3.1.5 on 2021-04-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210415_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='children',
        ),
        migrations.RemoveField(
            model_name='order',
            name='group',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rate',
        ),
    ]
