# Generated by Django 3.1.5 on 2021-04-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0052_auto_20210415_0919'),
        ('orders', '0006_auto_20210415_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='children',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tours.rate', verbose_name='Дети'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='group', to='tours.rate', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rate', to='tours.rate', verbose_name='Тариф'),
            preserve_default=False,
        ),
    ]
